doc: archive old version documentation
react-native-oh-library/react-native-image-sequence pull request #6
Opened 2024-12-02 08:32 UTC by leehom-liulihong

# Summary

归档 github 版本文档，迁移声明中新增说明

2024-12-03 07:19 UTC, Louis-C7 requested changes

2024-12-03 07:19 UTC, Louis-C7 commented on README.md
> +- The package name has been changed to `@react-native-ohos/rntpc_react-native-image-sequence` and is now available for direct download from npm.
@react-native-ohos/react-native-image-sequence

2024-12-03 07:19 UTC, Louis-C7 commented on README.md
> +- 包名已更改为 `@react-native-ohos/rntpc_react-native-image-sequence`，支持直接从 npm 下载。
@react-native-ohos/react-native-image-sequence

2024-12-03 08:08 UTC, leehom-liulihong commented on README.md
> +- 包名已更改为 `@react-native-ohos/rntpc_react-native-image-sequence`，支持直接从 npm 下载。
已修改

2024-12-03 08:08 UTC, leehom-liulihong commented on README.md
> +- The package name has been changed to `@react-native-ohos/rntpc_react-native-image-sequence` and is now available for direct download from npm.
已修改

2024-12-03 09:51 UTC, Louis-C7 requested changes

2024-12-03 09:51 UTC, Louis-C7 commented on README.md
> +- 包名已更改为 `@react-native-oh-tpl/react-native-image-sequence-2`，支持直接从 npm 下载。
@react-native-ohos/react-native-image-sequence

2024-12-03 09:51 UTC, Louis-C7 commented on README.md
> +- The package name has been changed to `@react-native-oh-tpl/react-native-image-sequence-2` and is now available for direct download from npm.
同上

2024-12-04 01:45 UTC, Louis-C7 approved these changes

2024-12-04 01:48 UTC, merged